# Dockerfile
# Use Node.js as the base image
FROM node:16

# Create a directory for the app
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port (match it to each service’s default port)
EXPOSE 4001

# Start the application
CMD ["node", "index.js"]
